export const sampleWeather = {
  current: 'Rainy',
  temperature: 24,
  humidity: 84,
  windSpeed: 12,
  summary: 'Heavy showers and slippery roads',
  icon: '🌧️',
};

export const sampleCongestion = [
  { id: 'c1', name: 'Marine Drive', level: 'High', color: '#ef4444', delay: '12 min' },
  { id: 'c2', name: 'Poondi Road', level: 'Medium', color: '#f59e0b', delay: '8 min' },
  { id: 'c3', name: 'City Junction', level: 'Low', color: '#22c55e', delay: '4 min' },
];

export const sampleHazards = [
  {
    id: 'h1',
    type: 'Pothole',
    severity: 'High',
    confidence: 0.92,
    distance: 0.6,
    location: { city: 'Chennai', address: 'Near Anna Salai' },
    latitude: 13.0827,
    longitude: 80.2707,
    timestamp: new Date(Date.now() - 40 * 60000).toISOString(),
    reporter: 'Aarthi',
    status: 'Pending',
    votes: 14,
    image: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=720&q=80',
  },
  {
    id: 'h2',
    type: 'Speedbump',
    severity: 'Medium',
    confidence: 0.78,
    distance: 1.2,
    location: { city: 'Adyar', address: 'Opposite Lagoon' },
    latitude: 13.0107,
    longitude: 80.2444,
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    reporter: 'Rohan',
    status: 'Verified',
    votes: 27,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=720&q=80',
  },
  {
    id: 'h3',
    type: 'Flooding',
    severity: 'High',
    confidence: 0.88,
    distance: 2.8,
    location: { city: 'T. Nagar', address: 'Mount Road Crossing' },
    latitude: 13.0521,
    longitude: 80.2175,
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    reporter: 'Meera',
    status: 'Pending',
    votes: 32,
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=720&q=80',
  },
];

export const sampleAlerts = [
  {
    id: 'a1',
    title: 'Community warning near Central Avenue',
    description: 'Multiple users reported a sinking pothole after last night’s storm.',
    timestamp: new Date(Date.now() - 18 * 60000).toISOString(),
    votes: 12,
  },
  {
    id: 'a2',
    title: 'Speedbump added ahead of shopping district',
    description: 'Drive slow: visibility is low and local road crews are active.',
    timestamp: new Date(Date.now() - 80 * 60000).toISOString(),
    votes: 8,
  },
];

export const sampleSensorReadings = [
  { day: 'Mon', potholes: 12, cracks: 8, flooding: 3 },
  { day: 'Tue', potholes: 18, cracks: 6, flooding: 2 },
  { day: 'Wed', potholes: 8, cracks: 5, flooding: 4 },
  { day: 'Thu', potholes: 15, cracks: 4, flooding: 5 },
  { day: 'Fri', potholes: 22, cracks: 9, flooding: 1 },
  { day: 'Sat', potholes: 30, cracks: 13, flooding: 8 },
  { day: 'Sun', potholes: 20, cracks: 11, flooding: 5 },
];

export const sampleStats = {
  totalHazards: 24,
  activeReports: 18,
  roadsCleared: 11,
  dangerousRoad: 'Anna Salai',
  bestTime: '5am - 8am',
  helpedUsers: 1240,
  reportCount: 46,
};

export const adminMockReports = [
  ...sampleHazards,
  {
    id: 'h4',
    type: 'Crack',
    severity: 'Low',
    confidence: 0.72,
    distance: 1.6,
    location: { city: 'Velachery', address: 'Velachery Main Road' },
    latitude: 13.0135,
    longitude: 80.2205,
    timestamp: new Date(Date.now() - 220 * 60000).toISOString(),
    reporter: 'Priya',
    status: 'Pending',
    votes: 8,
    image: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=720&q=80',
  },
  {
    id: 'h5',
    type: 'Pothole',
    severity: 'High',
    confidence: 0.92,
    distance: 0.9,
    location: { city: 'Adyar', address: 'Thiru Vi Ka Road' },
    latitude: 13.0125,
    longitude: 80.2450,
    timestamp: new Date(Date.now() - 320 * 60000).toISOString(),
    reporter: 'Karthik',
    status: 'Resolved',
    votes: 19,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=720&q=80',
  },
  {
    id: 'h6',
    type: 'Flooding',
    severity: 'Medium',
    confidence: 0.85,
    distance: 3.5,
    location: { city: 'T. Nagar', address: 'Habibullah Road' },
    latitude: 13.0550,
    longitude: 80.2160,
    timestamp: new Date(Date.now() - 140 * 60000).toISOString(),
    reporter: 'Meera',
    status: 'Ignored',
    votes: 6,
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=720&q=80',
  },
  {
    id: 'h7',
    type: 'Speedbump',
    severity: 'Medium',
    confidence: 0.78,
    distance: 2.0,
    location: { city: 'Chennai', address: 'New Washermenpet' },
    latitude: 13.1020,
    longitude: 80.2870,
    timestamp: new Date(Date.now() - 360 * 60000).toISOString(),
    reporter: 'Raja',
    status: 'Pending',
    votes: 11,
    image: 'https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&w=720&q=80',
  },
];

export const adminMockUsers = [
  { id: 'u1', fullName: 'Aarthi Kumar', email: 'aarthi@gmail.com', phone: '9876543210', city: 'Chennai', vehicle: 'Car', reportsCount: 14, joinDate: '2025-01-15', status: 'Active' },
  { id: 'u2', fullName: 'Rohan Sharma', email: 'rohan@gmail.com', phone: '9123456780', city: 'Adyar', vehicle: 'Bike', reportsCount: 9, joinDate: '2025-02-03', status: 'Active' },
  { id: 'u3', fullName: 'Meera Nair', email: 'meera@gmail.com', phone: '9988776655', city: 'T.Nagar', vehicle: 'Car', reportsCount: 22, joinDate: '2024-12-10', status: 'Active' },
  { id: 'u4', fullName: 'Karthik Raja', email: 'karthik@gmail.com', phone: '9871234560', city: 'Velachery', vehicle: 'Truck', reportsCount: 6, joinDate: '2025-03-01', status: 'Active' },
  { id: 'u5', fullName: 'Priya Devi', email: 'priya@gmail.com', phone: '9765432109', city: 'Mylapore', vehicle: 'Auto', reportsCount: 18, joinDate: '2025-01-28', status: 'Active' },
];

export const adminAnalytics = {
  weeklyData: [
    { day: 'Mon', submitted: 12, resolved: 8 },
    { day: 'Tue', submitted: 18, resolved: 14 },
    { day: 'Wed', submitted: 8, resolved: 6 },
    { day: 'Thu', submitted: 15, resolved: 11 },
    { day: 'Fri', submitted: 22, resolved: 19 },
    { day: 'Sat', submitted: 30, resolved: 22 },
    { day: 'Sun', submitted: 20, resolved: 16 },
  ],
  severityDist: [
    { name: 'High', value: 35, color: '#ef4444' },
    { name: 'Medium', value: 45, color: '#f59e0b' },
    { name: 'Low', value: 20, color: '#10b981' },
  ],
  typeBreakdown: [
    { type: 'Pothole', count: 42 },
    { type: 'Crack', count: 28 },
    { type: 'Speedbump', count: 19 },
    { type: 'Flooding', count: 15 },
    { type: 'Other', count: 8 },
  ],
  avgResolutionHours: 4.2,
  accuracyRate: 91,
  engagementScore: 84,
  peakHour: '8am - 10am',
};
