export const sampleReports = [
  {
    id: 'R-001',
    thumbnail: 'https://images.unsplash.com/photo-1529516549648-fd4c2e2f1e79?auto=format&fit=crop&w=600&q=80',
    type: 'Pothole',
    location: 'Anna Salai, Chennai',
    reporter: 'Aarthi',
    severity: 'High',
    status: 'Pending',
    confidence: 0.92,
    submittedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    latitude: 13.0827,
    longitude: 80.2707,
    notes: [],
    votes: 14,
    reason: null,
  },
  {
    id: 'R-002',
    thumbnail: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=600&q=80',
    type: 'Speedbump',
    location: 'Adyar, Chennai',
    reporter: 'Rohan',
    severity: 'Medium',
    status: 'Resolved',
    confidence: 0.78,
    submittedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    latitude: 13.0107,
    longitude: 80.2444,
    notes: [{ id: 'N-001', text: 'Verified with local crew.', createdAt: new Date(Date.now() - 3.5 * 3600000).toISOString() }],
    votes: 27,
    reason: null,
  },
  {
    id: 'R-003',
    thumbnail: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=600&q=80',
    type: 'Flooding',
    location: 'Mount Road, T. Nagar',
    reporter: 'Meera',
    severity: 'High',
    status: 'Pending',
    confidence: 0.88,
    submittedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    latitude: 13.0521,
    longitude: 80.2175,
    notes: [],
    votes: 32,
    reason: null,
  },
  {
    id: 'R-004',
    thumbnail: 'https://images.unsplash.com/photo-1564501046735-03f5f41b3d21?auto=format&fit=crop&w=600&q=80',
    type: 'Crack',
    location: 'Velachery, Chennai',
    reporter: 'Kavya',
    severity: 'Medium',
    status: 'Ignored',
    confidence: 0.61,
    submittedAt: new Date(Date.now() - 7 * 3600000).toISOString(),
    latitude: 12.9867,
    longitude: 80.2169,
    notes: [{ id: 'N-002', text: 'Marked as duplicate of prior report.', createdAt: new Date(Date.now() - 6.5 * 3600000).toISOString() }],
    votes: 9,
    reason: 'Duplicate Report',
  },
  {
    id: 'R-005',
    thumbnail: 'https://images.unsplash.com/photo-1465414829459-d228b58caf6e?auto=format&fit=crop&w=600&q=80',
    type: 'Missing Signage',
    location: 'Teynampet, Chennai',
    reporter: 'Naveen',
    severity: 'Low',
    status: 'Resolved',
    confidence: 0.74,
    submittedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    latitude: 13.0277,
    longitude: 80.2313,
    notes: [],
    votes: 5,
    reason: null,
  },
];

export const sampleUsers = [
  { id: 'U-001', name: 'Aarthi', email: 'aarthi@gmail.com', city: 'Chennai', reports: 14, joined: 'Jan 2025', status: 'Active' },
  { id: 'U-002', name: 'Rohan', email: 'rohan@roadguard.in', city: 'Chennai', reports: 9, joined: 'Feb 2025', status: 'Active' },
  { id: 'U-003', name: 'Meera', email: 'meera.s@roadguard.in', city: 'T. Nagar', reports: 5, joined: 'Mar 2025', status: 'Inactive' },
  { id: 'U-004', name: 'Kavya', email: 'kavya.r@roadguard.in', city: 'Velachery', reports: 8, joined: 'Jan 2025', status: 'Active' },
  { id: 'U-005', name: 'Naveen', email: 'naveen.v@roadguard.in', city: 'Adyar', reports: 6, joined: 'Apr 2025', status: 'Active' },
];

export const sampleAnalytics = {
  kpis: [
    { title: 'Total Reports', value: 846, trend: '+12%', icon: 'bar-chart', color: '#3B82F6', subtitle: '↑ 12% today' },
    { title: 'Pending', value: 124, trend: '⚠️', icon: 'clock', color: '#F59E0B', subtitle: 'Needs attention' },
    { title: 'Resolved', value: 692, trend: '+18%', icon: 'check-circle', color: '#22C55E', subtitle: 'This week' },
    { title: 'Active Users', value: 1240, trend: '👥', icon: 'users', color: '#06B6D4', subtitle: 'Online now' },
  ],
  timeSeries: [
    { date: 'Apr 1', submitted: 34, resolved: 26, ignored: 8 },
    { date: 'Apr 2', submitted: 42, resolved: 31, ignored: 10 },
    { date: 'Apr 3', submitted: 28, resolved: 22, ignored: 5 },
    { date: 'Apr 4', submitted: 56, resolved: 45, ignored: 9 },
    { date: 'Apr 5', submitted: 49, resolved: 35, ignored: 12 },
    { date: 'Apr 6', submitted: 60, resolved: 47, ignored: 11 },
    { date: 'Apr 7', submitted: 38, resolved: 29, ignored: 6 },
    { date: 'Apr 8', submitted: 45, resolved: 36, ignored: 7 },
    { date: 'Apr 9', submitted: 51, resolved: 42, ignored: 8 },
    { date: 'Apr 10', submitted: 55, resolved: 48, ignored: 6 },
    { date: 'Apr 11', submitted: 62, resolved: 54, ignored: 5 },
    { date: 'Apr 12', submitted: 48, resolved: 40, ignored: 7 },
    { date: 'Apr 13', submitted: 66, resolved: 58, ignored: 8 },
    { date: 'Apr 14', submitted: 58, resolved: 49, ignored: 9 },
  ],
  severityBreakdown: [
    { name: 'High', value: 38, color: '#EF4444' },
    { name: 'Medium', value: 41, color: '#F59E0B' },
    { name: 'Low', value: 21, color: '#22C55E' },
  ],
  topLocations: [
    { name: 'Anna Salai', count: 86, severity: 92 },
    { name: 'Adyar Bridge', count: 73, severity: 78 },
    { name: 'Mount Road', count: 64, severity: 82 },
    { name: 'Velachery Main Road', count: 59, severity: 68 },
    { name: 'T Nagar', count: 51, severity: 74 },
  ],
  typeBreakdown: [
    { name: 'Pothole', count: 312, color: '#3B82F6' },
    { name: 'Crack', count: 198, color: '#F59E0B' },
    { name: 'Speedbump', count: 146, color: '#22C55E' },
    { name: 'Flooding', count: 90, color: '#6366F1' },
    { name: 'Other', count: 100, color: '#94A3B8' },
  ],
  resolutionRate: 82,
  avgResolutionHours: 6.4,
  accuracyRate: 89,
  engagement: 4.5,
  peakHour: '5pm-7pm',
  activeDay: 'Thursday',
};

export const sampleActivity = [
  { id: 'A-001', action: 'Resolved', reportId: 'R-002', reportType: 'Speedbump', admin: 'RoadGuard Admin', timestamp: new Date(Date.now() - 140 * 60000).toISOString() },
  { id: 'A-002', action: 'Ignored', reportId: 'R-004', reportType: 'Crack', admin: 'RoadGuard Admin', timestamp: new Date(Date.now() - 210 * 60000).toISOString() },
  { id: 'A-003', action: 'Resolved', reportId: 'R-005', reportType: 'Missing Signage', admin: 'RoadGuard Admin', timestamp: new Date(Date.now() - 420 * 60000).toISOString() },
  { id: 'A-004', action: 'Escalated', reportId: 'R-003', reportType: 'Flooding', admin: 'RoadGuard Admin', timestamp: new Date(Date.now() - 540 * 60000).toISOString() },
];
